Nekomimi:
    API Provider: xxxxxx
    Model: xxxxxx
    Token: xx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Language: xx

TelegramBot:
    Token: xxxxxxxxxx:xxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx
    Language: xx
    UserName: xxxxxxx
    StreamingResponse: False
